#!/usr/bin/env bash
# Provision the Azure resources for the Databricks track:
#   - resource group
#   - ADLS Gen2 storage account (hierarchical namespace on) + one container
#   - Azure Databricks workspace (Premium SKU, required for Unity Catalog)
#   - Databricks Access Connector (managed identity UC uses to reach the storage)
#   - RBAC: Storage Blob Data Contributor for the access connector and for you
#
# Idempotent: safe to re-run. Writes the outputs to infra/azure/.env.azure
# (gitignored) for upload_raw.sh and the Databricks bundle.
#
# Usage:  bash infra/azure/provision.sh            # defaults below
#         AZ_LOCATION=centralindia bash infra/azure/provision.sh
set -euo pipefail

AZ_LOCATION="${AZ_LOCATION:-eastus}"
AZ_RG="${AZ_RG:-rg-home-credit}"
AZ_CONTAINER="${AZ_CONTAINER:-home-credit}"
AZ_DBX_WS="${AZ_DBX_WS:-dbw-home-credit}"
AZ_ACCESS_CONNECTOR="${AZ_ACCESS_CONNECTOR:-ac-home-credit}"

# Storage account names are global, 3-24 lowercase alphanumerics. Derive a
# stable suffix from the subscription id so re-runs land on the same account.
SUB_ID="$(az account show --query id -o tsv)"
AZ_STORAGE="${AZ_STORAGE:-sthomecredit${SUB_ID:0:8}}"
MY_OBJECT_ID="$(az ad signed-in-user show --query id -o tsv)"

HERE="$(cd "$(dirname "$0")" && pwd)"
OUT="$HERE/.env.azure"

echo "Subscription : $SUB_ID"
echo "Location     : $AZ_LOCATION"
echo "Resource grp : $AZ_RG"
echo "Storage      : $AZ_STORAGE / $AZ_CONTAINER"
echo "Workspace    : $AZ_DBX_WS"
echo

# The `az databricks` commands live in an extension; install silently on demand.
az config set extension.use_dynamic_install=yes_without_prompt >/dev/null
az provider register --namespace Microsoft.Databricks --wait >/dev/null
az provider register --namespace Microsoft.Storage --wait >/dev/null

echo "==> Resource group"
az group create --name "$AZ_RG" --location "$AZ_LOCATION" -o none

echo "==> ADLS Gen2 storage account (hierarchical namespace on)"
az storage account create \
  --name "$AZ_STORAGE" --resource-group "$AZ_RG" --location "$AZ_LOCATION" \
  --sku Standard_LRS --kind StorageV2 --enable-hierarchical-namespace true \
  --min-tls-version TLS1_2 --allow-blob-public-access false -o none
STORAGE_ID="$(az storage account show -n "$AZ_STORAGE" -g "$AZ_RG" --query id -o tsv)"

echo "==> Grant yourself Storage Blob Data Contributor (Owner alone has no data-plane rights)"
az role assignment create --role "Storage Blob Data Contributor" \
  --assignee-object-id "$MY_OBJECT_ID" --assignee-principal-type User \
  --scope "$STORAGE_ID" -o none

echo "==> Container $AZ_CONTAINER"
# RBAC propagation can lag by a minute; retry rather than fail on the first attempt.
for i in 1 2 3 4 5 6; do
  if az storage container create --name "$AZ_CONTAINER" --account-name "$AZ_STORAGE" \
       --auth-mode login -o none 2>/dev/null; then break; fi
  echo "   waiting for RBAC propagation ($i/6)..."; sleep 15
done

echo "==> Databricks workspace (Premium, takes 5-10 min on first run)"
az databricks workspace create \
  --name "$AZ_DBX_WS" --resource-group "$AZ_RG" --location "$AZ_LOCATION" \
  --sku premium -o none
WS_URL="$(az databricks workspace show -n "$AZ_DBX_WS" -g "$AZ_RG" --query workspaceUrl -o tsv)"

echo "==> Access connector (managed identity for Unity Catalog storage credential)"
az databricks access-connector create \
  --name "$AZ_ACCESS_CONNECTOR" --resource-group "$AZ_RG" --location "$AZ_LOCATION" \
  --identity-type SystemAssigned -o none
AC_ID="$(az databricks access-connector show -n "$AZ_ACCESS_CONNECTOR" -g "$AZ_RG" --query id -o tsv)"
AC_PRINCIPAL="$(az databricks access-connector show -n "$AZ_ACCESS_CONNECTOR" -g "$AZ_RG" --query identity.principalId -o tsv)"

echo "==> Grant the access connector Storage Blob Data Contributor on the account"
az role assignment create --role "Storage Blob Data Contributor" \
  --assignee-object-id "$AC_PRINCIPAL" --assignee-principal-type ServicePrincipal \
  --scope "$STORAGE_ID" -o none

cat > "$OUT" <<ENV
# Generated by infra/azure/provision.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ) — gitignored
AZ_LOCATION=$AZ_LOCATION
AZ_RG=$AZ_RG
AZ_STORAGE=$AZ_STORAGE
AZ_CONTAINER=$AZ_CONTAINER
AZ_DBX_WS=$AZ_DBX_WS
AZ_ACCESS_CONNECTOR_ID=$AC_ID
DATABRICKS_HOST=https://$WS_URL
# For the local pipeline: read the raw CSVs straight from ADLS
AZURE_DATA_URI=abfss://$AZ_CONTAINER@$AZ_STORAGE.dfs.core.windows.net/raw
ENV

echo
echo "Done. Outputs written to $OUT"
echo "Workspace URL: https://$WS_URL"
echo
echo "Next: bash infra/azure/upload_raw.sh"
